## Name: Thiago de Oliveira da Costa - StId: 2020005
### GitHub:  https://github.com/ThBrasilDaCosta/ML-Firewall-Inc-Traffic

### Project: Machine Learning Firewall Incoming Traffic.

##### Importing necessary labraries:

In [1]:
import pandas as pd
import numpy as np

##### Loading CSV file:

In [2]:
firewall_traffic = pd.read_csv('log2.csv')

##### Data Understanding:

In [3]:
firewall_traffic.shape

(65532, 12)

In [4]:
firewall_traffic.head(10)

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received,Action
0,57222,53,54587,53,177,94,83,2,30,1,1,allow
1,56258,3389,56258,3389,4768,1600,3168,19,17,10,9,allow
2,6881,50321,43265,50321,238,118,120,2,1199,1,1,allow
3,50553,3389,50553,3389,3327,1438,1889,15,17,8,7,allow
4,50002,443,45848,443,25358,6778,18580,31,16,13,18,allow
5,51465,443,39975,443,3961,1595,2366,21,16,12,9,allow
6,60513,47094,45469,47094,320,140,180,6,7,3,3,allow
7,50049,443,21285,443,7912,3269,4643,23,96,12,11,allow
8,52244,58774,2211,58774,70,70,0,1,5,1,0,allow
9,50627,443,16215,443,8256,1674,6582,31,75,15,16,allow

In [5]:
firewall_traffic.dtypes

Source Port              int64
Destination Port         int64
NAT Source Port          int64
NAT Destination Port     int64
Bytes                    int64
Bytes Sent               int64
Bytes Received           int64
Packets                  int64
Elapsed Time (sec)       int64
pkts_sent                int64
pkts_received            int64
Action                  object
dtype: object

In [6]:
firewall_traffic.describe()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received
count,65532.000000,65532.000000,65532.000000,65532.000000,6.553200e+04,6.553200e+04,6.553200e+04,6.553200e+04,65532.000000,65532.000000,65532.000000
mean,49391.969343,10577.385812,19282.972761,2671.049930,9.712395e+04,2.238580e+04,7.473815e+04,1.028660e+02,65.833577,41.399530,61.466505
std,15255.712537,18466.027039,21970.689669,9739.162278,5.618439e+06,3.828139e+06,2.463208e+06,5.133002e+03,302.461762,3218.871288,2223.332271
min,0.000000,0.000000,0.000000,0.000000,6.000000e+01,6.000000e+01,0.000000e+00,1.000000e+00,0.000000,1.000000,0.000000
25%,49183.000000,80.000000,0.000000,0.000000,6.600000e+01,6.600000e+01,0.000000e+00,1.000000e+00,0.000000,1.000000,0.000000
50%,53776.500000,445.000000,8820.500000,53.000000,1.680000e+02,9.000000e+01,7.900000e+01,2.000000e+00,15.000000,1.000000,1.000000
75%,58638.000000,15000.000000,38366.250000,443.000000,7.522500e+02,2.100000e+02,4.490000e+02,6.000000e+00,30.000000,3.000000,2.000000
max,65534.000000,65535.000000,65535.000000,65535.000000,1.269359e+09,9.484772e+08,3.208818e+08,1.036116e+06,10824.000000,747520.000000,327208.000000

In [7]:
firewall_traffic.isna().sum()

Source Port             0
Destination Port        0
NAT Source Port         0
NAT Destination Port    0
Bytes                   0
Bytes Sent              0
Bytes Received          0
Packets                 0
Elapsed Time (sec)      0
pkts_sent               0
pkts_received           0
Action                  0
dtype: int64

In [8]:
firewall_traffic.loc[firewall_traffic.duplicated()]

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received,Action
268,21268,62609,0,0,146,146,0,1,0,1,0,deny
351,48706,23393,0,0,60,60,0,1,0,1,0,deny
593,65003,57470,0,0,78,78,0,1,0,1,0,deny
632,443,49988,0,0,82,82,0,1,0,1,0,deny
661,10669,49756,0,0,60,60,0,1,0,1,0,deny
...,...,...,...,...,...,...,...,...,...,...,...,...
65517,54874,445,0,0,70,70,0,1,0,1,0,drop
65519,49784,445,0,0,70,70,0,1,0,1,0,drop
65521,42995,26467,0,0,62,62,0,1,0,1,0,deny
65522,53314,64097,0,0,66,66,0,1,0,1,0,deny
65531,54867,445,0,0,70,70,0,1,0,1,0,drop

In [9]:
firewall_traffic.columns

Index(['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received',
       'Action'],
      dtype='object')

##### Data cleaning:

In [10]:
firewall_traffic = firewall_traffic.loc[~firewall_traffic.duplicated(subset=['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received',
       'Action'])].reset_index(drop=True).copy()

In [11]:
firewall_traffic

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received,Action
0,57222,53,54587,53,177,94,83,2,30,1,1,allow
1,56258,3389,56258,3389,4768,1600,3168,19,17,10,9,allow
2,6881,50321,43265,50321,238,118,120,2,1199,1,1,allow
3,50553,3389,50553,3389,3327,1438,1889,15,17,8,7,allow
4,50002,443,45848,443,25358,6778,18580,31,16,13,18,allow
...,...,...,...,...,...,...,...,...,...,...,...,...
57165,51710,43069,65147,43069,70,70,0,2,8,2,0,allow
57166,63691,80,13237,80,314,192,122,6,15,4,2,allow
57167,50964,80,13485,80,4680740,67312,4613428,4675,77,985,3690,allow
57168,54871,445,0,0,70,70,0,1,0,1,0,drop
57169,54870,445,0,0,70,70,0,1,0,1,0,drop

In [12]:
firewall_traffic.shape

(57170, 12)

In [13]:
firewall_traffic.describe()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received
count,57170.000000,57170.000000,57170.000000,57170.000000,5.717000e+04,5.717000e+04,5.717000e+04,5.717000e+04,57170.000000,57170.000000,57170.000000
mean,50532.499738,8052.147035,22048.739549,3054.123491,1.113147e+05,2.564701e+04,8.566766e+04,1.177065e+02,75.116547,47.279255,70.427200
std,13880.680957,16513.145167,22141.986286,10363.545911,6.015189e+06,4.098545e+06,2.637029e+06,5.495436e+03,322.519323,3446.210063,2380.254144
min,0.000000,0.000000,0.000000,0.000000,6.000000e+01,6.000000e+01,0.000000e+00,1.000000e+00,0.000000,1.000000,0.000000
25%,49450.000000,53.000000,0.000000,0.000000,7.000000e+01,7.000000e+01,0.000000e+00,1.000000e+00,0.000000,1.000000,0.000000
50%,54013.000000,443.000000,16362.500000,53.000000,1.930000e+02,9.400000e+01,9.000000e+01,2.000000e+00,26.000000,1.000000,1.000000
75%,58574.000000,445.000000,41883.750000,443.000000,1.139000e+03,5.080000e+02,6.690000e+02,1.000000e+01,31.000000,5.000000,4.000000
max,65534.000000,65535.000000,65535.000000,65535.000000,1.269359e+09,9.484772e+08,3.208818e+08,1.036116e+06,10824.000000,747520.000000,327208.000000

In [14]:
firewall_traffic['Action'].unique()

array(['allow', 'drop', 'deny', 'reset-both'], dtype=object)

##### Applying encoding method:

In [15]:
firewall_traffic['Action'].unique()

array(['allow', 'drop', 'deny', 'reset-both'], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)
ohetransform = ohe.fit_transform(firewall_traffic[['Action']])

In [17]:
ohetransform = pd.DataFrame(ohetransform, columns=ohe.categories_[0])

In [18]:
ohetransform

       allow  deny  drop  reset-both
0        1.0   0.0   0.0         0.0
1        1.0   0.0   0.0         0.0
2        1.0   0.0   0.0         0.0
3        1.0   0.0   0.0         0.0
4        1.0   0.0   0.0         0.0
...      ...   ...   ...         ...
57165    1.0   0.0   0.0         0.0
57166    1.0   0.0   0.0         0.0
57167    1.0   0.0   0.0         0.0
57168    0.0   0.0   1.0         0.0
57169    0.0   0.0   1.0         0.0

[57170 rows x 4 columns]

In [19]:
firewall_traffic = pd.concat([firewall_traffic, ohetransform], axis=1).drop(columns = ['Action'])

In [20]:
firewall_traffic.head()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received,allow,deny,drop,reset-both
0,57222,53,54587,53,177,94,83,2,30,1,1,1.0,0.0,0.0,0.0
1,56258,3389,56258,3389,4768,1600,3168,19,17,10,9,1.0,0.0,0.0,0.0
2,6881,50321,43265,50321,238,118,120,2,1199,1,1,1.0,0.0,0.0,0.0
3,50553,3389,50553,3389,3327,1438,1889,15,17,8,7,1.0,0.0,0.0,0.0
4,50002,443,45848,443,25358,6778,18580,31,16,13,18,1.0,0.0,0.0,0.0

In [21]:
firewall_traffic.tail(50)

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received,allow,deny,drop,reset-both
57120,55216,53,59483,53,711,87,624,2,30,1,1,1.0,0.0,0.0,0.0
57121,58956,53,19380,53,213,89,124,2,30,1,1,1.0,0.0,0.0,0.0
57122,55850,443,8932,443,2883,642,2241,13,135,6,7,1.0,0.0,0.0,0.0
57123,64385,443,4632,443,3677,1168,2509,17,120,8,9,1.0,0.0,0.0,0.0
57124,56456,443,10392,443,3528,1162,2366,10,120,5,5,1.0,0.0,0.0,0.0
57125,51000,443,31109,443,41713,34380,7333,67,333,38,29,1.0,0.0,0.0,0.0
57126,51709,40705,43195,40705,70,70,0,2,8,2,0,1.0,0.0,0.0,0.0
57127,5394,23,5394,23,124,60,64,2,5,1,1,1.0,0.0,0.0,0.0
57128,50370,80,12726,80,318,192,126,6,28,4,2,1.0,0.0,0.0,0.0
57129,50359,80,41698,80,318,192,126,6,28,4,2,1.0,0.0,0.0,0.0
57130,41340,80,50400,80,2426,1540,886,14,23,8,6,1.0,0.0,0.0,0.0
57131,61308,443,22375,443,44341,5858,38483,102,195,42,60,1.0,0.0,0.0,0.0
57132,50367,80,15574,80,318,192,126,6,28,4,2,1.0,0.0,0.0,0.0
57133,30023,3389,30023,3389,4145,1976,2169,22,19,13,9,1.0,0.0,0.0,0.0
57134,55015,443,8354,443,1786,172,1614,7,120,3,4,1.0,0.0,0.0,0.0
57135,55726,27015,16348,27015,1173,924,249,6,30,3,3,1.0,0.0,0.0,0.0
57136,56457,443,49133,443,3654,1144,2510,10,120,5,5,1.0,0.0,0.0,0.0
57137,59021,443,44226,443,4596,1442,3154,24,154,11,13,1.0,0.0,0.0,0.0
57138,53518,29500,52778,29500,320,140,180,6,7,3,3,1.0,0.0,0.0,0.0
57139,51688,47961,35098,47961,66,66,0,1,5,1,0,1.0,0.0,0.0,0.0
57140,57031,53,9800,53,170,87,83,2,31,1,1,1.0,0.0,0.0,0.0
57141,60375,32277,60465,32277,70,70,0,1,5,1,0,1.0,0.0,0.0,0.0
57142,57904,443,64826,443,7912,3215,4697,23,20,12,11,1.0,0.0,0.0,0.0
57143,50343,80,49722,80,22233,10123,12110,37,28,16,21,1.0,0.0,0.0,0.0
57144,50360,80,16489,80,318,192,126,6,28,4,2,1.0,0.0,0.0,0.0
57145,50438,3389,50438,3389,3429,1474,1955,16,16,8,8,1.0,0.0,0.0,0.0
57146,50361,80,40866,80,318,192,126,6,28,4,2,1.0,0.0,0.0,0.0
57147,50368,80,46672,80,318,192,126,6,28,4,2,1.0,0.0,0.0,0.0
57148,49681,53,1706,53,170,87,83,2,30,1,1,1.0,0.0,0.0,0.0
57149,35608,443,62915,443,5776,1880,3896,19,272,11,8,1.0,0.0,0.0,0.0
57150,57137,53,7336,53,711,87,624,2,30,1,1,1.0,0.0,0.0,0.0
57151,5938,22455,0,0,60,60,0,1,90,1,0,1.0,0.0,0.0,0.0
57152,36226,60038,0,0,66,66,0,1,91,1,0,1.0,0.0,0.0,0.0
57153,49559,53,6355,53,164,84,80,2,31,1,1,1.0,0.0,0.0,0.0
57154,57292,53,56725,53,170,87,83,2,31,1,1,1.0,0.0,0.0,0.0
57155,58574,443,3429,443,3447,788,2659,13,135,6,7,1.0,0.0,0.0,0.0
57156,56985,53,45052,53,711,87,624,2,31,1,1,1.0,0.0,0.0,0.0
57157,50269,445,0,0,66,66,0,1,0,1,0,0.0,0.0,1.0,0.0
57158,50270,445,0,0,66,66,0,1,0,1,0,0.0,0.0,1.0,0.0
57159,50268,445,0,0,66,66,0,1,0,1,0,0.0,0.0,1.0,0.0
57160,54013,37965,0,0,66,66,0,1,0,1,0,0.0,1.0,0.0,0.0
57161,49783,445,0,0,70,70,0,1,0,1,0,0.0,0.0,1.0,0.0
57162,55142,26467,0,0,66,66,0,1,0,1,0,0.0,1.0,0.0,0.0
57163,53848,36237,0,0,62,62,0,1,0,1,0,0.0,1.0,0.0,0.0
57164,65323,53,33275,53,356,118,238,2,30,1,1,1.0,0.0,0.0,0.0
57165,51710,43069,65147,43069,70,70,0,2,8,2,0,1.0,0.0,0.0,0.0
57166,63691,80,13237,80,314,192,122,6,15,4,2,1.0,0.0,0.0,0.0
57167,50964,80,13485,80,4680740,67312,4613428,4675,77,985,3690,1.0,0.0,0.0,0.0
57168,54871,445,0,0,70,70,0,1,0,1,0,0.0,0.0,1.0,0.0
57169,54870,445,0,0,70,70,0,1,0,1,0,0.0,0.0,1.0,0.0

In [22]:
firewall_traffic.columns

Index(['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received', 'allow',
       'deny', 'drop', 'reset-both'],
      dtype='object')

##### Decision Tree ML model:

In [23]:
independent_features = ['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received']

dependent_features = ['allow', 'deny', 'drop', 'reset-both']

X = firewall_traffic[independent_features]
y = firewall_traffic[dependent_features]

In [24]:
print(X)

       Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0            57222                53            54587                    53
1            56258              3389            56258                  3389
2             6881             50321            43265                 50321
3            50553              3389            50553                  3389
4            50002               443            45848                   443
...            ...               ...              ...                   ...
57165        51710             43069            65147                 43069
57166        63691                80            13237                    80
57167        50964                80            13485                    80
57168        54871               445                0                     0
57169        54870               445                0                     0

         Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
0          177          94              83        2                  30
1         4768        1600            3168       19                  17
2          238         118             120        2                1199
3         3327        1438            1889       15                  17
4        25358        6778           18580       31                  16
...        ...         ...             ...      ...                 ...
57165       70          70               0        2                   8
57166      314         192             122        6                  15
57167  4680740       67312         4613428     4675                  77
57168       70          70               0        1                   0
57169       70          70               0        1                   0

       pkts_sent  pkts_received
0              1              1
1             10              9
2              1              1
3              8              7
4             13             18
...          ...            ...
57165          2              0
57166          4              2
57167        985           3690
57168          1              0
57169          1              0

[57170 rows x 11 columns]

In [25]:
print(y)

       allow  deny  drop  reset-both
0        1.0   0.0   0.0         0.0
1        1.0   0.0   0.0         0.0
2        1.0   0.0   0.0         0.0
3        1.0   0.0   0.0         0.0
4        1.0   0.0   0.0         0.0
...      ...   ...   ...         ...
57165    1.0   0.0   0.0         0.0
57166    1.0   0.0   0.0         0.0
57167    1.0   0.0   0.0         0.0
57168    0.0   0.0   1.0         0.0
57169    0.0   0.0   1.0         0.0

[57170 rows x 4 columns]

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=17, test_size = 0.2)

In [28]:
X_train.shape

(45736, 11)

In [29]:
X_test.shape

(11434, 11)

In [30]:
y_train.shape

(45736, 4)

In [31]:
y_test.shape

(11434, 4)

In [32]:
from sklearn.tree import DecisionTreeClassifier

In [33]:
dtc = DecisionTreeClassifier()

In [34]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [35]:
y_pred = dtc.predict(X_test)

In [44]:
from sklearn.metrics import classification_report

In [45]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7589
           1       0.99      0.99      0.99      1548
           2       1.00      1.00      1.00      2291
           3       0.33      0.50      0.40         6

   micro avg       1.00      1.00      1.00     11434
   macro avg       0.83      0.87      0.85     11434
weighted avg       1.00      1.00      1.00     11434
 samples avg       1.00      1.00      1.00     11434

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [46]:
dtc.feature_importances_

array([3.02321392e-03, 3.29014676e-01, 1.69090629e-04, 3.71062351e-04,
       2.77994496e-04, 3.12281694e-04, 1.03438604e-04, 1.25854445e-02,
       6.53869030e-01, 2.73767845e-04, 0.00000000e+00])

In [37]:
from sklearn.metrics import confusion_matrix